package com.example.myrecyclerview;

import java.util.ArrayList;

class CharacterData {
    private static String[][] data = new String[][]{
            {"Monkey D. Luffy", "Luffy memiliki cita-cita menjadi Raja Bajak Laut setelah bertemu dengan Shanks Si Rambut Merah yang singgah di pulau kelahirannya, Fusha. Topi jerami yang menjadi ciri khasnya adalah pemberian dari Shanks dan dia berjanji akan memberikan topi itu kembali kepadanya saat mereka bertemu kembali.\n" +
                    "\n" +
                    "Luffy adalah pemakan buah iblis Gomu Gomu no Mi sehingga ia menjadi manusia karet. kemampuan ini membuatnya tubuhnya memiliki atribut yang sama dengan karet, seperti melar, peredam listrik, dsb.\n" +
                    "\n" +
                    "Ciri khas bertarungnya adalah menyerang dengan memanjangkan bagian tubuhnya. Semua nama jurusnya selalu diawali dengan kata \"Gomu-gomu\" dan kemudian diikuti dengan nama senjata atau artileri (contoh: 'Gomu Gomu no Pistol', 'Gomu Gomu no Bazooka', 'Gomu Gomu no Gatling', dll).\n" +
                    "\n" +
                    "Gear Second: Teknik mempercepat aliran darah tetapi organ tubuhnya tidak hancur karena atribut karet pada tubuhnya. Efek dari Gear Second ini adalah kecepatan atau agility meningkat. Kata \"jet\" juga ditambahan dalam nama jurusnya (contoh: Gomu Gomu no Jet pistol). Jika ditambah dengan Haki, tinjunya jadi menimbulkan efek ledakan.\n" +
                    "\n" +
                    "Gear Third: Teknik memberpesar tulang dengan meniupnya seperti balon. Efek dari Gear Third adalah kekuatan serangannya meningkat, namun kecepatan serangan menurun. Kata \"Gigant\" juga ditambahan dalam nama jurusnya (contoh: Gomu Gomu no Gigant Pistol). Jika ditambahkan haki tangannya menjadi hitam dan semakin keras.\n" +
                    "\n" +
                    "Gear Four: Teknik memperbesar badan seukuran gorilla, dengan menggabungkan boushuku haki. Kekuatan ini mirip dengan tubuh gorilla dengan daya hancur yang sangat kuat. Dan ditambah dengan kekuatan tinjuan yang bisa mental di udara. (kekuatan ini muncul di dressrosa sewaktu melawan sichibukai Donquixote Doflamingo).\n" +
                    "\n" +
                    "Hybrid: Gabungan dari Gear Second dan Gear Third. Kata \"Shell\" ditambahan dalam nama jurusnya. ", "https://steemitimages.com/p/7ohP4FeQn62jm1q1vDFjB7sDirXEJG6RVY4fbgCyiBuqotqxxBASB7Whn899JXdT1JmxsMtfvBLgiwPtuXEfMat5m8brb2nwERUa?format=match&mode=fit&width=640"},
            {"Roronoa Zoro", "Merupakan kru pertama yang ikut bergabung dalam Kelompok Topi Jerami dan menjabat sebagai wakil kapten. Teknik bertarungnya menggunakan 3 pedang yang merupakan pedang langka dalam dunia One Piece. Zoro memiliki cita-cita untuk menjadi pendekar pedang terkuat di dunia, mewarisi cita-cita sahabat masa kecilnya, Kuina, yang meninggal karena kecelakaan. ", "https://upload.wikimedia.org/wikipedia/id/a/a4/Roronoa_Zoro.jpg"},
            {"Nami", "Navigator dari Kelompok Topi Jerami yang dapat merasakan perubahan cuaca dengan tubuhnya. Kemampuan lain selain navigasi adalah mencuri dan membuat peta. Cita-cita dari Nami adalah membuat peta seluruh dunia. Senjata yang digunakan adalah tongkat dengan berbagai modifikasi dari Usopp. ", "https://upload.wikimedia.org/wikipedia/id/9/9a/Namiface.jpg"},
            {"Usopp", "Penembak jitu di Kelompok Bajak Laut Topi Jerami. Bercita-cita menjadi penembak jitu pemberani di seluruh lautan dan ingin pergi ke Pulau Elbaf. Ayahnya, Yasopp, adalah seorang penembak jitu di Kelompok Bajak Laut Shanks. Sangat suka berbohong, dan bercerita yang tinggi-tinggi. Bertarung dengan memakai tembakan katapel dengan peluru unik dan jebakan-jebakan. Setelah 2 tahun latihan mampu mengendalikan Pop Green, tumbuhan yang bisa tumbuh dengan agresif dan cepat. Di Arc Dressrosa Usopp mendapat kekuatan haki penglihatan, yang mana dia bisa melihat Sugar (anggota keluaraga bajak laut Donquixote Doflamingo) ingin menyentuh Luffy dan Law dengan tujuan merobah mereka menjadi mainan, dan dia bisa melihat jelas keberadaan sugar dan menembakkan jebakan yang berisi gambar dirinya dengan mata dan lidah menjulur keluar. Menurut dirinya sendiri, dia termasuk 3 orang terlemah di kelompok, selain Nami dan Chopper. Walaupun termasuk 3 terlemah, dia merupakan orang yang berani bertarung melawan sang kapten Monkey D. Luffy dan membakar bendera Pemerintah Dunia. ", "https://upload.wikimedia.org/wikipedia/id/d/d8/Usopp2.jpg"},
            {"Vinsmoke Sanji", "Koki di anggota Bajak Laut Topi Jerami dan merupakan rival Roronoa Zoro. Sanji merupakan seorang bangsawan dari negeri kuat Germa 66 ia melarikan diri dari kerajaannya menjadi seorang koki di sebuah kapal . Dia seorang Koki yang bercita-cita menemukan lautan legendaris di mana semua sumber bahan makanan berasal, yaitu All Blue. Ia juga merupakan murid dari Zeff si Kaki Merah, koki handal dari Restoran Baratie yang dulunya bajak laut. Sanji sangat genit terhadap wanita. Sanji mempunyai prinsip yaitu tidak akan melukai wanita walaupun harus mati. Sanji menggunakan kedua kakinya untuk bertarung dan tidak pernah menggunakan tangannya karena menurutnya, tangan adalah harta karun bagi seorang koki. Sanji bertarung dengan teknik tendangan yang sangat kuat. Dia juga bisa memakai tenknik \"Diable Jump / Diable Jumble\" yang membuat kakinya mengeluarkan api. Teknik ini bisa memperkuat tendangannya dan memberikan efek terbakar pada musuhnya. Termasuk 3 anggota terkuat Kelompok Topi Jerami. Selain itu jurus andalan terbarunya adalah Hell Memories yang mana jurus ini selalu mengingatkan dia sewaktu di pulau Okama tempat Emporio Ivankov (anggota Pasukan Revolusi) dan jurus ini lebih hebat daya bakarnya ketimbang Diable Jambe dan Sky Walk yang bisa berjalan di atas langit.", "https://cdn.myanimelist.net/s/common/uploaded_files/1476881633-e71f544272d9907d6041c44dec7f97fd.png"},
            {"Tony Tony Chopper", "Dokter yang berwujud rusa kutub ini mempunyai tujuh wujud perubahan. Chopper mengemban keinginan dari dokter terhebat di dunia dokter Hiluluk, yang bercita-cita menyembuhkan segala penyakit yang ada di dunia. Dia pemakan buah iblis Hito Hito sehingga dapat berbicara layaknya manusia. Kekuatan buah Hito-Hito juga membuatnya bisa berubah menjadi berbagai macam wujud termasuk menjadi monster. Setelah 2 tahun, dia bisa memakai wujud monsternya tanpa kehilangan kesadaran.", "https://vignette.wikia.nocookie.net/onepiece/images/a/af/Tony_Tony_Chopper_Anime_Post_Timeskip_Infobox.png/revision/latest?cb=20190127203911&path-prefix=id"},
            {"Nico Robin", "Arkeolog satu-satunya di dunia yang tersisa dari Pulau Ohara yang meneliti asal usul penyandang inisial 'D' melalui Poneglyph yang mungungkapkan kejadian yang sebenarnya pada sejarah 100 tahun yang hilang. Merupakan buruan paling dicari oleh pihak pemerintah dunia karena dianggap sebagai iblis yang dapat mengacaukan perdamaian dunia. Hal ini dibuktikan dengan nilai buruan pada saat umurnya 8 tahun sangat tinggi. Pemakan buah iblis Hana Hana sehingga dapat menggandakan anggota tubuhnya di mana saja (tetapi lebih sering menggandakan tangannya). Bertarung dengan mengandakan tubuhnya, bisa digunakan untuk berbagai variasi jurus (seperti menumbuhkan tangan di tubuh lawan lalu memukulnya). Saat menggunakan kekuatannya dia menyilangkan tangannya.", "http://jeremia-mangas.j.e.pic.centerblog.net/o/e1cbdb3a.jpg"},
            {"Franky", "Cyborg sekaligus Tukang kayu kapal yang bercita-cita membangun kapal impian, kapal yang mampu mengarungi seluruh lautan seperti kapal Raja Bajak Laut Gol D. Roger, Oro Jackson, yang dibuat oleh Tom. Saat Tom ditangkap oleh Angkatan Laut, Frangky berniat menghentikan kereta api atas laut yang mengangkut Tom ke Ennies Lobby. Akibatnya, ia tertabrak kereta tersebut dan nyaris meninggal. Untuk bertahan hidup, ia mengubah struktur tubuhnya dengan berbagai teknologi hingga menjadi Cyborg. Teknik bertarung Franky cukup bervariasi. Ia menggunakan senjata yang tersembunyi di seluruh tubuhnya, dan menggunakan Cola sebagai bahan bakar. 2 tahun kemudian, setelah berkumpul kembali, Frangky merakit ulang tubuhnya dengan teknologi canggih dari Angkatan Laut, yang merupakan hasil penelitian dari Vegapunk, seorang ilmuwan dari Angkatan Laut. Selain itu dia sekarang telah mengembangkan robot tempur yang ia namakan \"General Iron Pirates\". dan robot ini bisa berubah menjadi sepeda motor tempur dan tank baja. ", "https://vignette.wikia.nocookie.net/onepiece/images/3/30/Franky_Anime_Pre_Timeskip_Infobox.png/revision/latest?cb=20160109195827"},
            {"Brook", "Manusia tengkorak berambut afro dan juga seorang pemusik yang direkrut setelah peristiwa Thriller Bark. Dia merupakan bajak laut yang berjanji pada seekor paus yang bernama Laboon dan bercita-cita untuk meneruskan perjalanan hingga Raftel, pulau ujung dunia dan berjanji akan kembali lagi menemui Laboon. Bertarung dengan menggunakan pedang dan biolanya. Kekuatan musiknya bisa menghipnotis orang yang mendengarkan lagunya dan juga bisa menidurkan orang. Pemakan buah iblis Yomi Yomi yang artinya hidup kembali. Sebenarnya dia sudah lama meninggal, tetapi karena kekuatan buah iblis ini arwahnya kembali dan menemukan jasadnya yang telah tinggal tulang belulang. Setelah 2 tahun berlatih mampu menyambung tubuhnya yang putus, pedangnya bisa membekukan dan bisa mengeluarkan roh dari jasad tengkoraknya. ", "https://upload.wikimedia.org/wikipedia/id/e/e2/Brook_One_Piece.jpg"},
            {"Jinbei", "Manusia-ikan hiu paus dan merupakan ahli \"Fishman Karate\", mampu memanipulasi air sebagai senjata sekaligus armor. Tumbuh di daerah Fishman District di Pulau Fishman, Jimbei awalnya bergabung dengan tentara kerajaan dan kemudian Kelompok Bajak Laut Matahari, di mana dia menjadi kapten kedua setelah kematian Fisher Tiger. Sebagai ganti kepada Pemerintah Dunia atas statusnya sebagai Shichibukai, Jinbei membubarkan krunya. Jinbei mengundurkan posisinya dari Pemerintah Dunia setelah menolak bergabung melawan Kru Bajak Laut Whitebeard, protektor Pulau Fishman. Dua tahun kemudian, Jinbei menolak sementara ajakan untuk bergabung dengan kru Topi Jerami, menyatakan bahwa dia harus menyelesaikan urusannya yang belum selesai sebelum benar-benar bergabung dengan mereka. ", "https://vignette.wikia.nocookie.net/fairypirates/images/b/b1/Jimbei.png/revision/latest?cb=20161022123005"},
    };

    static ArrayList<Character> getListData() {
        ArrayList<Character> list = new ArrayList<>();
        for (String[] aData : data) {
            Character character = new Character();
            character.setName(aData[0]);
            character.setDesc(aData[1]);
            character.setPhoto(aData[2]);
            list.add(character);
        }
        return list;
    }
}
